/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author OSCAR
 */
public class paginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form paginaPrincipal
     */
    public paginaPrincipal() {
        initComponents();
        
       
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(pantalla.width, pantalla.height);

        // Maximizar la ventana (opcional)
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        contenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInventario = new javax.swing.JMenu();
        Ingresar = new javax.swing.JMenuItem();
        registroInventario = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuInformes = new javax.swing.JMenu();
        nemuSoporte = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        menuInventario.setText("Inventario");

        Ingresar.setText("Ingresar producto");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        menuInventario.add(Ingresar);

        registroInventario.setText("Inventario");
        registroInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroInventarioActionPerformed(evt);
            }
        });
        menuInventario.add(registroInventario);

        jMenuBar1.add(menuInventario);

        menuCompras.setText("Compras");
        jMenuBar1.add(menuCompras);

        menuInformes.setText("Informes");
        jMenuBar1.add(menuInformes);

        nemuSoporte.setText("Soporte");
        jMenuBar1.add(nemuSoporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        registrarProducto rp=new registrarProducto();
        // Obtener las dimensiones de la pantalla
         Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
         int width = dimension.width;
         int height = dimension.height;

// Establecer el tamaño de la ventana
         rp.setSize(width, height);
        
        rp.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(rp,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void registroInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroInventarioActionPerformed
        // TODO add your handling code here:
        inventario ri=new inventario();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
         ri.setSize(pantalla.width, pantalla.height);

        // Maximizar la ventana (opcional)
       
         ri.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(ri,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
        
    }//GEN-LAST:event_registroInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ingresar;
    private javax.swing.JPanel contenido;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu nemuSoporte;
    private javax.swing.JMenuItem registroInventario;
    // End of variables declaration//GEN-END:variables
}
